mymongodb:
   image: mongo:latest
   container_name: "mymongodb"
   ports:
     - 27017:27017
springboot-mongodb:
   build: .
   dockerfile: docker/Dockerfile
   container_name: springboot-mongodb
   ports:
     - 8580:8080
   links:
     - mymongodb    